# Generated by Django 5.1.3 on 2024-12-08 03:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discount_Card', '0003_alter_coupon_valid_from_alter_coupon_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
